site_name: NIKA

dev_addr: 127.0.0.1:8002

extra_css:
  - _assets/main.css
extra_javascript:
  - _assets/scg.min.js
  - _assets/main.js

plugins:
  - search                                       
  - i18n:
      default_language: en
      languages:
        en: English
        ru: Русский
      no_translation:
        ru: "Эта страница не переведена на русский язык"
        en: "This page isn't translated to English"
      translate_nav:
        ru:
          Home: "Главная"
          Build: "Сборка"
          Development: "Разработка"
          Project structure: "Структура проекта"
          Agents: "Агенты"
          Non-atomic action interpretation agent: "Агент интерпретации неатомарных действий"
          Changelog: "Список изменений"
          Subsystems: "Подсистемы"
          License: "Лицензия"


nav:
  - Home: index.md
  - Home: index.ru.md
  - Build:
    - Docker: build/docker-build.md
    - Docker: build/docker-build.ru.md
    - Debian-based distros / Linux: build/linux-build.md
    - Debian-based distros / Linux: build/linux-build.ru.md
  - Development:
    - Git-workflow: dev/git-workflow.md
    - Git-workflow: dev/git-workflow.ru.md
    - Pull requests: dev/pr.md
    - Pull requests: dev/pr.ru.md
    - Codestyle: dev/codestyle.md
    - Codestyle: dev/codestyle.ru.md
    - Project structure: dev/project_structure.md
    - Project structure: dev/project_structure.ru.md
  - Agents:
    - Non-atomic action interpretation agent: agents/nonAtomicActionInterpretationAgent.md
    - Non-atomic action interpretation agent: agents/nonAtomicActionInterpretationAgent.ru.md
  - Subsystems:
     - scl-machine: subsystems/scl-machine.md
     - scl-machine: subsystems/scl-machine.ru.md
  - Changelog: changelog.md
  - Thirdparty: thirdparty.md
  - Thirdparty: thirdparty.ru.md
  - License: license.md

theme: 
    name: material
    language: en

extra:
  # Default mkdocs-material alternate links for untranslated pages
  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/#site-language-selector
  # For translated pages the language name is replaced by the string configured in i18n plugin
  # secction and link is replaced by the link to the translated page
  alternate:
    - name: "Home"
      link: ""
      lang: en

    - name: "Главная"
      link: index.ru
      lang: ru


markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.details
  - pymdownx.superfences
